### ISSUE TITLE
Branch 3.0

### ISSUE THREAD

**Issue by ineiti** [CrowdNotifier/libcrowdnotifier#27]
This branch should include the following changes:
- [ ] Add a `Criticality` field
  - where? what type?
- [ ] Change the `message` to a protobuf containing:
  - `associatedData`
  - `countryData`
 - [ ] Update computation of identities to include domain seperation and explicit structures

**Comment by wouterl** [comment]
More things:

- [ ]  Update computation of identities to include domain separation and explicit structuring
